### ISSUE TITLE
尝试运行在linux平台异常

### ISSUE THREAD

**Issue by chuncui0207** [tangxuehua/ecommon#13]
汤总：
我尝试把NameServer和Broker放到docker for linux，抛出了ConsoleEventHandlerService.cs未找到kernel32.dll的异常。
有什么处理方法吗?

**Comment by swpudp** [comment]
使用try-catch可以屏蔽该错误，运行得起来，但是后来发现每次重启机器chunk文件全没有了

**Comment by tangxuehua** [comment]
ConsoleEventHandlerService这个类已经去掉，请使用最新版本再试试。
