### ISSUE TITLE
ChunkHeader 类的FromStream 方法存在无效参数

### ISSUE THREAD

**Issue by CarsonPan** [tangxuehua/ecommon#16]
在ChunkHeader 以及ChunkFooter类中的静态方法FromStream ，存在没有使用的参数stream

![001](https://user-images.githubusercontent.com/31815291/39796169-7f564138-5387-11e8-8c84-4e5b902eafd1.PNG)

**Comment by tangxuehua** [comment]
这个应该是你的chunk文件和ecommon读取chunk文件的配置信息有不一致导致。
