### ISSUE TITLE
1.4.7版本处此是否可能造成内存溢出

### ISSUE THREAD

**Issue by niaoked** [tangxuehua/ecommon#3]
你好：
   我在项目中正在使用1.4.7版本，PC程序作为客户端，硬件设备作为服务端。设备正常开机时内存使用正常，由于程序运行在服务器上，所以晚上设备关机后程序仍然会周期性尝试连接设备，第二一早上会发现程序内存达到2G多，正常运行时400MB左右。
我查了一下代码，发现：
public void ReconnectToServer()
        {
            _connection.ConnectionClosed -= OnConnectionClosed;
            _connection = new TcpClientConnector(_setting.TcpConfiguration).ConnectTo(Guid.NewGuid(), _localEndPoint, _serverEndPoint, OnConnectionEstablished, OnConnectionFailed);
            _connection.ConnectionClosed += OnConnectionClosed;
            _connection.ReceiveAsync(OnRawDataReceived);
｝
在每次重连时会创建一个新的TcpClientConnector对象，而在TcpClientConnector中会初始化一个Timer:
 _timer = new Timer(TimerCallback, null, CheckPeriodMs, Timeout.Infinite);

而这个Timer在重连之前没有得到显式释放，这会不会是造成不断重连多次后内存占用越来越大？

**Comment by tangxuehua** [comment]
请用最新版本：2.0.2试试，最新版本中代码已经不是这样了。






在2015年12月13 08时30分, "niaoked"<notifications@github.com>写道:



你好：
  我在项目中正在使用147版本，PC程序作为客户端，硬件设备作为服务端。设备正常开机时内存使用正常，由于程序运行在服务器上，所以晚上设备关机后程序仍然会周期性尝试连接设备，第二一早上会发现程序内存达到2G多，正常运行时400MB左右。
我查了一下代码，发现：
public void ReconnectToServer()
       {
           _connectionConnectionClosed -= OnConnectionClosed;
           _connection = new TcpClientConnector(_settingTcpConfiguration)ConnectTo(GuidNewGuid(), _localEndPoint, _serverEndPoint, OnConnectionEstablished, OnConnectionFailed);
           _connectionConnectionClosed += OnConnectionClosed;
           _connectionReceiveAsync(OnRawDataReceived);
｝
在每次重连时会创建一个新的TcpClientConnector对象，而在TcpClientConnector中会初始化一个Timer:
_timer = new Timer(TimerCallback, null, CheckPeriodMs, TimeoutInfinite);

而这个Timer在重连之前没有得到显式释放，这会不会是造成不断重连多次后内存占用越来越大？
