### ISSUE TITLE
SocketUtils.ShutdownSocket(_socket);

### ISSUE THREAD

**Issue by hanxinimm** [tangxuehua/ecommon#9]
![qq 20161208154554](https://cloud.githubusercontent.com/assets/13499426/21001861/a5000020-bd5d-11e6-8d1a-94ee2d7c7754.png)
WEBAPI站点调试，经常发生运行一次就必须要重启IIS释放资源才能再次链接

**Comment by tangxuehua** [comment]
看错误是端口重复监听导致的问题，你要分析一下为何会出现socket server没有关闭啊。这个和ecommon本身没有关系。
